# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Micky Blogs
tagline:          'A Jekyll theme'
description:      'Fumbling with tech. Gadget reviews. Contact <a href="https://twitter.com/heymicky" target="_blank">@mheymicky</a>.'
url:              http://heymicky.github.io
baseurl:          /

author:
  name:           'Micky Hingorani'
  url:            http://mickyhingorani.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/heymicky.github.io
